//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://services.excelra.com/wsdl/authenticationservice/authentication/AppService/" +
    "v01/AppAS", ClrNamespace="services.excelra.com.wsdl.authenticationservice.authentication.AppService.v01.App" +
    "AS")]

namespace services.excelra.com.wsdl.authenticationservice.authentication.AppService.v01.AppAS
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AppAuthenticationRequest", Namespace="http://services.excelra.com/wsdl/authenticationservice/authentication/AppService/" +
        "v01/AppAS")]
    public partial class AppAuthenticationRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ApplicationField;
        
        private string ApplicationVersionField;
        
        private string IPField;
        
        private string PWDField;
        
        private string SystemIDField;
        
        private string SystemLoginUserField;
        
        private string UserNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string Application
        {
            get
            {
                return this.ApplicationField;
            }
            set
            {
                this.ApplicationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string ApplicationVersion
        {
            get
            {
                return this.ApplicationVersionField;
            }
            set
            {
                this.ApplicationVersionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string IP
        {
            get
            {
                return this.IPField;
            }
            set
            {
                this.IPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string PWD
        {
            get
            {
                return this.PWDField;
            }
            set
            {
                this.PWDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string SystemID
        {
            get
            {
                return this.SystemIDField;
            }
            set
            {
                this.SystemIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string SystemLoginUser
        {
            get
            {
                return this.SystemLoginUserField;
            }
            set
            {
                this.SystemLoginUserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AppAuthenticationResponse", Namespace="http://services.excelra.com/wsdl/authenticationservice/authentication/AppService/" +
        "v01/AppAS")]
    public partial class AppAuthenticationResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private services.excelra.com.wsdl.authenticationservice.authentication.AppService.v01.AppAS.AcknowledgementInfo AcknowledgementField;
        
        private string DepartmentField;
        
        private string EmailField;
        
        private string EmpIDField;
        
        private string ProjectField;
        
        private string UserNameField;
        
        private string UserNextManagerField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public services.excelra.com.wsdl.authenticationservice.authentication.AppService.v01.AppAS.AcknowledgementInfo Acknowledgement
        {
            get
            {
                return this.AcknowledgementField;
            }
            set
            {
                this.AcknowledgementField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Department
        {
            get
            {
                return this.DepartmentField;
            }
            set
            {
                this.DepartmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmpID
        {
            get
            {
                return this.EmpIDField;
            }
            set
            {
                this.EmpIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Project
        {
            get
            {
                return this.ProjectField;
            }
            set
            {
                this.ProjectField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserNextManager
        {
            get
            {
                return this.UserNextManagerField;
            }
            set
            {
                this.UserNextManagerField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AcknowledgementInfo", Namespace="http://services.excelra.com/wsdl/authenticationservice/authentication/AppService/" +
        "v01/AppAS")]
    public partial class AcknowledgementInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ConfirmationCodeField;
        
        private string DescriptionField;
        
        private bool IsErrorField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConfirmationCode
        {
            get
            {
                return this.ConfirmationCodeField;
            }
            set
            {
                this.ConfirmationCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsError
        {
            get
            {
                return this.IsErrorField;
            }
            set
            {
                this.IsErrorField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://services.excelra.com/wsdl/authenticationservice/authentication/AppService/" +
    "v01/AppAS", ConfigurationName="IAppAS")]
public interface IAppAS
{
    
    [System.ServiceModel.OperationContractAttribute(Action="AuthenticateUser", ReplyAction="http://services.excelra.com/wsdl/authenticationservice/authentication/AppService/" +
        "v01/AppAS/IAppAS/AuthenticateUserResponse")]
    services.excelra.com.wsdl.authenticationservice.authentication.AppService.v01.AppAS.AppAuthenticationResponse AuthenticateUser(services.excelra.com.wsdl.authenticationservice.authentication.AppService.v01.AppAS.AppAuthenticationRequest appAuthenticationrequest);
    
    [System.ServiceModel.OperationContractAttribute(Action="TestResponse", ReplyAction="http://services.excelra.com/wsdl/authenticationservice/authentication/AppService/" +
        "v01/AppAS/IAppAS/TestResponseResponse")]
    string TestResponse(string stringinput);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IAppASChannel : IAppAS, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class AppASClient : System.ServiceModel.ClientBase<IAppAS>, IAppAS
{
    
    public AppASClient()
    {
    }
    
    public AppASClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public AppASClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public AppASClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public AppASClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }

    //public object AppGetUserEmailFromLDAP(AppCheckUserNameInLDAPAndReturnEmail appCheckUserNameInLDAPAndReturnEmail)
    //{
    //    throw new NotImplementedException();
    //}

    public services.excelra.com.wsdl.authenticationservice.authentication.AppService.v01.AppAS.AppAuthenticationResponse AuthenticateUser(services.excelra.com.wsdl.authenticationservice.authentication.AppService.v01.AppAS.AppAuthenticationRequest appAuthenticationrequest)
    {
        return base.Channel.AuthenticateUser(appAuthenticationrequest);
    }
    
    public string TestResponse(string stringinput)
    {
        return base.Channel.TestResponse(stringinput);
    }
}
